### ISSUE TITLE
How can i disable raven when my environment is local ?

### ISSUE THREAD

**Issue by manuirrazabal** [twineis/raven-php#12]

**Comment by pulkitjalan** [comment]
Setting the dsn in the config enables it, and leaving it blank disables it

**Comment by manuirrazabal** [comment]
I found the way. if you don't wanna leave blank. Set up in your .env file you environment and Exceptions -> Handler . in render functions. 

// Stop Sentry/Raven reporting for local enviroment.
       if (app()->environment('local') && $this->shouldReport($e)) {
            app('Twine\Raven\Client')->server = null;
        }

In this way you can avoid re writing your settings all the time.
