### ISSUE TITLE
Monolog processors are not run

### ISSUE THREAD

**Issue by tremby** [twineis/raven-php#6]
The config file shows how to add Monolog processors, and gives an example of a GitProcessor. Whether I add this one or my own UserDataProcessor or other Monolog processors such as MemoryUsageProcessor, they do not run and so their data is not attached to the messages passed to Sentry.

**Comment by pulkitjalan** [comment]
I've updated master with what I think should work. I can't test it right now so will test tomorrow. If you get a chance to test please let me know.

**Comment by tremby** [comment]
Yes, that fixes it. Thanks. Please tag a release.
