### ISSUE TITLE
Messages include context as JSON string

### ISSUE THREAD

**Issue by tremby** [twineis/raven-php#7]
When I look at the submitted issues in the Sentry interface, they all have a JSON-encoded representation of the context data after the message, such as `test warning {"user":{"id":1,"email":"test@example.com"}} []`. This particular issue was logged with `\Log::warning('test warning');`, with context added via a processor. I get the same result if instead of the processor I add the context data as you do in the example in the readme.

If I look at the JSON submitted to Sentry I see that this JSON-encoded context data is present in the message string. It seems to me this should not be there.

**Comment by tremby** [comment]
It turns out the fix is simple -- it's just a matter of removing ` %context% %extra%` from the format string in AbstractServiceProvider line 42. I could provide this as a pull request if you like? Or is this by design? If so, why?

**Comment by pulkitjalan** [comment]
This was originally copied from [sentry ravens own example](https://docs.sentry.io/clients/php/integrations/laravel/) (before [getsentry/sentry-laravel](https://github.com/getsentry/sentry-laravel)), but context and extra are added via the RavenHandler in monolog so its not required here. Removed it now and tagged a new release.

Thanks
