### ISSUE TITLE
With recommended configuration uncaught exceptions are logged twice

### ISSUE THREAD

**Issue by tremby** [twineis/raven-php#8]
The readme suggests configuring Laravel to log uncaught exceptions and then call parent::report on the exception too.

But the parent report method also logs the message. This means it gets reported twice.

They are reported with different messages, which I'll talk about in a different ticket.

![screen shot 2016-12-08 at 10 07 48 am](https://cloud.githubusercontent.com/assets/199635/21021656/49ba45ce-bd2e-11e6-996c-c3d518491ab0.png)

It seems to me it would be better not to suggest adding anything to the report method at all, and have it logged just once.

**Comment by pulkitjalan** [comment]
hmm yea i can see why that would happen...

The example should probably be:

```php
/**
 * Report or log an exception.
 *
 * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
 *
 * @param  \Exception  $e
 * @return void
 */
public function report(Exception $e)
{
    if ($this->shouldReport($e)) {
        \Log::error($e->getMessage(), ['exception' => $e]);
    } else {
        return parent::report($e);
    }
}
```

This would resolve the issue.

I suppose however if there was an elegant solution to issue #9 the above would not be required at all...

**Comment by tremby** [comment]
Yeah, that's what I was hoping for.

Your suggestion above only works around the other issue, since both branches of your conditional above do essentially the same thing, just with different formatting.
